workflow:
  format: v2.3
  block:
  - blockname: 3dangularMoment
    order: workflow
    list:
    - group:
      - outputname: ElectricConfiguration
        outputtype: parts
    - group:
      - methodname: AttributeS3dAngularMoment
        methodtype: method
        outputname: S3d
        outputtype: parts
      - methodname: AttributeL3dAngularMoment
        methodtype: method
        outputname: L3d
        outputtype: parts
      - methodname: AttributeJ3dAngularMoment
        methodtype: method
        outputname: J3d
        outputtype: parts
  - blockname: J4fangularMoment
    order: workflow
    list:
    - group:
      - outputname: ElectricConfiguration
        outputtype: parts
    - group:
      - methodname: AttributeJ4fAngularMoment
        methodtype: method
        outputname: J4f
        outputtype: parts
      - methodname: selectgJ
        methodtype: function
        outputname: gJ
        outputtype: parts


  - blockname: J4fangularMomentProjection
    order: workflow
    list:
    - group:
      - methodname: AttributeJ4fAngularMoment
        methodtype: method
        outputname: J4f
        outputtype: parts
      - outputname: gJ
        outputtype: parts
    - group:
      - methodname: (gJ-1)J4f
        methodtype: parts
        outputname: AttributeJ4fSpinDirectionProjection
        outputtype: parts
      - methodname: (2-gJ)J4f
        methodtype: parts
        outputname: AttributeJ4fOrbitalDirectionProjection
        outputtype: parts

  - blockname: numberofelectron
    order: workflow
    list:
    - group:
      - outputname: ElectricConfiguration
        outputtype: parts
    - group:
      - methodname: evaluate_s_electron
        methodtype: function
        outputname: sOrbitalNumberOfElectrons
        outputtype: parts
  - blockname: numberofelectron
    order: workflow
    list:
    - group:
      - outputname: ElectricConfiguration
        outputtype: parts
    - group:
      - methodname: evaluate_p_electron
        methodtype: function
        outputname: pOrbitalNumberOfElectrons
        outputtype: parts
  - blockname: numberofelectron
    order: workflow
    list:
    - group:
      - outputname: ElectricConfiguration
        outputtype: parts
    - group:
      - methodname: evaluate_d_electron
        methodtype: function
        outputname: dOrbitalNumberOfElectrons
        outputtype: parts
  - blockname: numberofelectron
    order: workflow
    list:
    - group:
      - outputname: ElectricConfiguration
        outputtype: parts
    - group:
      - methodname: evaluate_f_electron
        methodtype: function
        outputname: fOrbitalNumberOfElectrons
        outputtype: parts

